//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public OrderMaster()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public System.Guid MasterId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
